In [6]:
import open3d as o3d
import numpy as np
import sys
import os
import copy
sys.path.append('..')
import open3d_tutorial as o3dtut
o3dtut.interactive= not 'CI' in os.environ


In [2]:
demo_data = o3d.data.DemoCropPointCloud()

In [9]:
def ICP(source,target,transformation):
    source_temp =copy.deepcopy(source)
    target_temp =copy.deepcopy(target)
    source_temp.paint_uniform_color([1,0.7,0])
    target_temp.paint_uniform_color([0,1.7,0.7])
    source_temp.transform(transformation)

    o3d.visualization.draw_geometries([source_temp,target_temp])


In [18]:
source =o3d.io.read_point_cloud(demo_data.point_cloud_path)
target = o3d.io.read_point_cloud(demo_data.point_cloud_path)
threshold=0.2
trans_init = np.asarray([[0.862, 0.011, -0.507, 0.5],
                         [-0.139, 0.967, -0.215, 0.7],
                         [0.487, 0.255, 0.835, -1.4], [0.0, 0.0, 0.0, 1.0]])
ICP(source,target,trans_init)

[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]


In [17]:
print("Inline Alignment")
evalution =o3d.pipelines.registration.evaluate_registration(source,target,threshold,trans_init)
print(evalution)

Inline Alignment
RegistrationResult with fitness=5.550570e-01, inlier_rmse=1.070000e-01, and correspondence_set size of 108865
Access transformation to get result.


In [19]:
print("Applying Point-to-Point ICP")
reg2pip = o3d.pipelines.registration.registration_icp(source,target,threshold,trans_init,o3d.pipelines.registration.TransformationEstimationPointToPoint())
print(reg2pip)
print("Transformation is: ")
print(reg2pip.transformation)
ICP(source,target,reg2pip.transformation)

Applying Point-to-Point ICP
RegistrationResult with fitness=8.600185e-01, inlier_rmse=8.326683e-02, and correspondence_set size of 168678
Access transformation to get result.
Transformation is: 
[[ 0.99087272  0.01540784 -0.13265069 -0.00701575]
 [-0.01461294  0.99994268  0.01198974  0.03104075]
 [ 0.13225622 -0.01059392  0.99134204 -0.32848701]
 [ 0.          0.          0.          1.        ]]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation opera

## Changing the maximum number of iteration

In [23]:
print("Applying to point-to-point ICP: ")
reg2pip = o3d.pipelines.registration.registration_icp(source,target,threshold,trans_init,o3d.pipelines.registration.TransformationEstimationPointToPoint(),o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=4000))
print(reg2pip)
print("Tranformation Matrix: ")
print(reg2pip.transformation)
ICP(source,target,reg2pip.transformation)

Applying to point-to-point ICP: 
RegistrationResult with fitness=1.000000e+00, inlier_rmse=3.551191e-03, and correspondence_set size of 196133
Access transformation to get result.
Tranformation Matrix: 
[[ 9.99766953e-01 -9.45072252e-04 -5.03828504e-04 -2.37788272e-03]
 [ 1.98828533e-04  1.00011674e+00  2.27523632e-04 -1.01727557e-03]
 [-3.34066754e-07 -7.84830676e-04  1.00024932e+00  1.74520140e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[Open3D WARNING] invalid color in PaintUniformColor, clipping to [0, 1]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: