In [2]:
import open3d as o3d
import numpy as np
import os
import sys
sys.path.append('..')
import open3d_tutorial as o3dtut
o3dtut.interactive = not 'CI' in os.environ

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
pcd = o3d.io.read_point_cloud('./data/scan1/scan.ply')

In [4]:
print(pcd)

PointCloud with 1328541 points.


In [5]:
print(np.asarray(pcd.points))

[[ 0.72000003  2.27999997  0.90814102]
 [ 0.73500001  2.27999997  0.90746802]
 [ 0.73500001  2.29500008  0.90726   ]
 ...
 [-4.36499977 -1.45500004  0.40464801]
 [-4.36331987 -1.45500004  0.41999999]
 [-4.3499999  -1.44672     0.41999999]]


In [8]:
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 


In [17]:
scan2 = o3d.io.read_point_cloud('./data/scan3/scan.ply')

In [18]:
print(scan2)

PointCloud with 1450966 points.


In [19]:
print(np.asarray(scan2.points))

[[ 0.94499999  2.15989995  0.61500001]
 [ 0.94484198  2.16000009  0.61500001]
 [ 0.94499999  2.16000009  0.60807002]
 ...
 [-3.77999997 -0.375      -1.49128997]
 [-3.7650001  -0.375      -1.49728   ]
 [-3.75818992 -0.375      -1.5       ]]


In [20]:
o3d.visualization.draw_geometries([scan2])

In [21]:
scan3 = o3d.io.read_point_cloud("./data/scan4/scan.ply")

In [22]:
print(scan3)


PointCloud with 974542 points.


In [23]:
np.asarray(scan3.points)

array([[ 1.72616005,  2.51999998,  0.60000002],
       [ 1.72739995,  2.53500009,  0.60000002],
       [ 1.72678006,  2.51999998,  0.61500001],
       ...,
       [ 0.105     ,  3.26999998, -1.44254005],
       [ 0.105     ,  3.28500009, -1.45212996],
       [ 0.105     ,  3.25500011, -1.45670998]])

In [24]:
o3d.visualization.draw_geometries([scan3])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 


In [25]:
scan4 = o3d.io.read_point_cloud('./data/scan3/scan.ply')

In [26]:
scan4

PointCloud with 1450966 points.

In [27]:
np.asarray(scan4.points)

array([[ 0.94499999,  2.15989995,  0.61500001],
       [ 0.94484198,  2.16000009,  0.61500001],
       [ 0.94499999,  2.16000009,  0.60807002],
       ...,
       [-3.77999997, -0.375     , -1.49128997],
       [-3.7650001 , -0.375     , -1.49728   ],
       [-3.75818992, -0.375     , -1.5       ]])

In [28]:
o3d.visualization.draw_geometries([scan4])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
