In [4]:
import open3d as o3d
import numpy as np
import os
import sys
sys.path.append('..')
import open3d_tutorial as o3dtut
o3dtut.interactive = not 'CI' in os.environ

In [5]:
pcd = o3d.io.read_point_cloud('./data/scan.ply')

In [6]:
print(pcd)

PointCloud with 1328541 points.


In [7]:
print(np.asarray(pcd.points))

[[ 0.72000003  2.27999997  0.90814102]
 [ 0.73500001  2.27999997  0.90746802]
 [ 0.73500001  2.29500008  0.90726   ]
 ...
 [-4.36499977 -1.45500004  0.40464801]
 [-4.36331987 -1.45500004  0.41999999]
 [-4.3499999  -1.44672     0.41999999]]


In [ ]:
o3d.visualization.draw_geometries